In [ ]:
#Eugene Fotsing
#Data from CTEC128
#jupiter Notebook

In [15]:
import pandas as pd

df = pd.read_csv('C:\\Users\\eugen\\OneDrive\\Documents\\Bowie state\\Fall 2024\\CTEC128\\Project\\Rought Data\\csv_hca\\psam_h06.csv')
df

,RT,SERIALNO,DIVISION,PUMA,REGION,ST,ADJHSG,ADJINC,WGTP,NP,...,WGTP71,WGTP72,WGTP73,WGTP74,WGTP75,WGTP76,WGTP77,WGTP78,WGTP79,WGTP80
0,H,2022GQ0000033,9,6509,4,6,1000000,1042311,0,1,...,0,0,0,0,0,0,0,0,0,0
1,H,2022GQ0000039,9,6501,4,6,1000000,1042311,0,1,...,0,0,0,0,0,0,0,0,0,0
2,H,2022GQ0000041,9,8101,4,6,1000000,1042311,0,1,...,0,0,0,0,0,0,0,0,0,0
3,H,2022GQ0000067,9,8303,4,6,1000000,1042311,0,1,...,0,0,0,0,0,0,0,0,0,0
4,H,2022GQ0000070,9,6712,4,6,1000000,1042311,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167257,H,2022HU1446425,9,2906,4,6,1000000,1042311,32,3,...,8,36,36,10,36,29,8,33,32,36
167258,H,2022HU1446431,9,5918,4,6,1000000,1042311,67,2,...,73,113,20,70,64,65,65,122,116,68
167259,H,2022HU1446436,9,8301,4,6,1000000,1042311,77,1,...,64,19,148,79,79,126,82,84,142,114
167260,H,2022HU1446447,9,2908,4,6,1000000,1042311,176,5,...,269,274,179,239,163,162,57,271,191,53
167261,H,2022HU1446451,9,3752,4,6,1000000,1042311,70,3,...,79,67,71,123,70,20,78,20,24,64

In [21]:
df2 = pd.read_csv('C:\\Users\\eugen\\OneDrive\\Documents\\Bowie state\\Fall 2024\\CTEC128\\Project\\Rought Data\\cvs_hca_2017\\psam_h06.csv')
df2

,RT,SERIALNO,DIVISION,PUMA,REGION,ST,ADJHSG,ADJINC,WGTP,NP,...,WGTP71,WGTP72,WGTP73,WGTP74,WGTP75,WGTP76,WGTP77,WGTP78,WGTP79,WGTP80
0,H,2017000000014,9,6703,4,6,1000000,1011189,59,3,...,64,63,54,16,100,65,61,69,17,101
1,H,2017000000017,9,110,4,6,1000000,1011189,74,4,...,140,73,126,67,21,72,27,117,64,113
2,H,2017000000023,9,7901,4,6,1000000,1011189,111,0,...,114,190,181,31,31,100,108,119,99,190
3,H,2017000000025,9,1906,4,6,1000000,1011189,63,1,...,17,57,60,61,64,20,68,69,99,62
4,H,2017000000036,9,6710,4,6,1000000,1011189,75,3,...,22,134,128,20,82,107,22,26,79,78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157729,H,2017001536739,9,6710,4,6,1000000,1011189,0,1,...,0,0,0,0,0,0,0,0,0,0
157730,H,2017001536743,9,2901,4,6,1000000,1011189,0,1,...,0,0,0,0,0,0,0,0,0,0
157731,H,2017001536747,9,3900,4,6,1000000,1011189,0,1,...,0,0,0,0,0,0,0,0,0,0
157732,H,2017001536756,9,2500,4,6,1000000,1011189,0,1,...,0,0,0,0,0,0,0,0,0,0
157733,H,2017001536763,9,2901,4,6,1000000,1011189,0,1,...,0,0,0,0,0,0,0,0,0,0